### ISSUE TITLE
Create wrapper 'client' class to manage keys & Mapeo (project) instances

### ISSUE THREAD

**Issue by gmaclennan** [digidem/comapeo-core#130]
Naming? `MultiMapeo`? `MapeoManager`?

- [ ] manage key pairs
- [ ] create Mapeo instances as needed within `getProject` (skip closing instances for now)
- [ ] read projects table for project info
- [ ] generate keypair for creating a new project, and persist the private key somewhere (securely)
- [ ] use master key for encrypting storage of project secret key
- [ ] figure out how to index project datatypes across multiple projects

- Adding invite namespace tracked (and estimated) in #103

Notes:

A project creator will have a secret key associated with the project (the project key is the public key of this keypair). This is the private key for the project creator's auth core. Other project members derive their secret keys from the project key, so creating an instance only needs the secret key for the project creator.

Ideas: 

```ts
class Client {
  // Future: change to LRU
  #projects = new Map()
  
  getProject(projectId) {
    const projectKey = getKey(projectId)
    if (!projectKey) throw new Error('Project doesn\'t exist')
    let project = this.#projects.get(projectId)
    if (!project) {
      project = new Mapeo({ projectKey })
      this.#projects.set(projectId, project)
    }
    return project
  }
}
```

Initial task list:

- [x] #167
- [x] #171
- [x] #165
- [x]  Add generic encrypt/decrypt methods to @mapeo/crypto 
  - https://github.com/digidem/mapeo-crypto/issues/3)
- [x]  Add KeyManager static method for generating project keypair (unrelated to rootkey)
  - https://github.com/digidem/mapeo-crypto/issues/4)
- [x]  update core client docs `client.createProject()` to return a project id, not project instance
  - https://github.com/digidem/mapeo-core-docs/issues/11
- [x] #168
- [x] #166

**Comment by achou11** [comment]
Initial tasks:

- [ ]  Add projectInfo indexing to MapeoProject, accept IndexWriter instance as constructor parameter (projectInfoIndexWriter.batch() to be called with any projectInfo records found in hypercores, after validating that docId matches projectId).
- [ ]  Decide what a “projectId” is - is it the project key, the discovery ID, or something else (e.g. a different hash of the project key)
- [ ]  Create a drizzle table schema definition to project keys
- [ ]  Add generic encrypt/decrypt methods to @mapeo/crypto
- [ ]  Add KeyManager static method for generating project keypair (unrelated to rootkey)
- [ ]  update core client docs `client.createProject()` to return a project id, not project instance
- [ ]  Implement `createProject()`
- [ ]  Add package.json script for generating client schema migration SQL

**Comment by achou11** [comment]
marking this as completed as we've added the foundations for the client class aside from the invite namespace, which are tracked in #198 and #212
