### ISSUE TITLE
Rename to `@comapeo/core`, bump to v1

### ISSUE THREAD

**Issue by tomasciccola** [digidem/comapeo-core#752]

**Comment by EvanHahn** [comment]
IMO, this should be done in two separate steps:

1. Change the name and publish the new package
2. Bump the version (should be done last minute)

I think we can do the first one whenever.

**Comment by tomasciccola** [comment]
I think the steps for this should roughly be the same as described here -> https://github.com/digidem/mapeo-schema/issues/194#issuecomment-2338350812
