### ISSUE TITLE
Add support for serving Styled Map Package maps

### ISSUE THREAD

**Issue by achou11** [digidem/comapeo-core#827]
### Description

We want to be able to serve offline maps that follow the format described in https://github.com/digidem/styled-map-package/. 

Ideally, I think this eventually replaces the "legacy" Mapeo approach that we currently support. For now, can probably build this functionality side-by-side.

### Tasks

- [ ] Expose functionality for importing and retrieving information about an SMP-based map.
  - importing = persisting the file path of the SMP file on the device to core.
  - based on app requirements, we'll need the following information about an SMP map:
    - date added
    - storage used
    - name

- ~Implement a Fastify plugin for serving the SMP file based on the location from ^~

**Comment by EvanHahn** [comment]
Seems reasonable to me, at least at a high level.

We already have a Fastify plugin in the `styled-map-package` module, if helpful: <https://github.com/digidem/styled-map-package/blob/0ede1b97bcdd0feb1df775025d0a7063dae6bf37/lib/server.js>

**Comment by achou11** [comment]
> Seems reasonable to me, at least at a high level.
> 
> We already have a Fastify plugin in the `styled-map-package` module, if helpful: https://github.com/digidem/styled-map-package/blob/0ede1b97bcdd0feb1df775025d0a7063dae6bf37/lib/server.js

Ah nice! Didn't see that - hopefully means less work then 👍
