### ISSUE TITLE
Convert "want hints" into want bitfields

### ISSUE THREAD

**Issue by gmaclennan** [digidem/comapeo-core#905]
A "want hint" is a list of filename filters for the blob hyperdrive(s), that is sent between peers.

A peer receiving a "want hint" should use the hyperdrive blobIndex to convert that want hint into a bitfield for the hyperdrive blob core.

This bitfield(s) can then be passed to the sync API.

**Comment by EvanHahn** [comment]
Done in 3d1c94b36314a32995766e9e43b4ea61504b1026.
